/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes.dex : \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/com/verizon/subscriber/BuildConfig.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/com/verizon/subscriber/R$attr.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/com/verizon/subscriber/R$drawable.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/com/verizon/subscriber/R$string.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/com/verizon/subscriber/R$xml.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/com/verizon/subscriber/R.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/com/verizon/subscriber/VerizonSubscriber.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$1.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$2$1.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$2$2.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$2.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$3$1.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$3$2.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$3$3.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$3$4.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$3.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$4$1.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$4$2.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$4$3.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$4$4.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$4.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$5$1.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$5.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$6$1.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification$6.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/classes/org/apache/cordova/dialogs/Notification.class \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/dexedLibs/classes-e323832cf9e2c3bfec8c819ee7625ce7.jar \
