/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/VerizonSubscriber.ap_ \
 : /Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-hdpi/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-land-hdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-land-ldpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-land-mdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-land-xhdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-ldpi/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-mdpi/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-port-hdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-port-ldpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-port-mdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-port-xhdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/drawable-xhdpi/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/values/strings.xml \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/res/xml/config.xml \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-hdpi/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-land-hdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-land-ldpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-land-mdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-land-xhdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-ldpi/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-mdpi/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-port-hdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-port-ldpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-port-mdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-port-xhdpi/screen.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/res/drawable-xhdpi/icon.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/_where-is-www.txt \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/cordova.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/cordova_plugins.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/img \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/index.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/bootstrap-theme.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/bootstrap-theme.css.map \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/bootstrap.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/bootstrap.css.map \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/component.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/font-awesome.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/images \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/jqm-demos.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/jquery.mobile.flatui.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/ladda-themeless.min.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/main.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/opensans.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/pageslider.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/Flat-UI-Icons-24.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/Flat-UI-Icons-24.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/fontawesome-webfont.eot \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/fontawesome-webfont.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/fontawesome-webfont.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/fontawesome-webfont.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/FontAwesome.otf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/glyphicons-halflings-regular.eot \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/glyphicons-halflings-regular.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/glyphicons-halflings-regular.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/glyphicons-halflings-regular.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/glyphicons-halflings-regular.woff2 \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/lato-black.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/lato-black.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/lato-bold.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/lato-bold.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/lato-italic.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/lato-italic.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/lato-regular.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/lato-regular.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Bold-webfont.eot \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Bold-webfont.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Bold-webfont.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Bold-webfont.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Bold-webfont.woff2 \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-ExtraBold-webfont.eot \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-ExtraBold-webfont.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-ExtraBold-webfont.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-ExtraBold-webfont.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-ExtraBold-webfont.woff2 \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Regular-webfont.eot \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Regular-webfont.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Regular-webfont.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Regular-webfont.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Regular-webfont.woff2 \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Semibold-webfont.eot \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Semibold-webfont.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Semibold-webfont.ttf \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Semibold-webfont.woff \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/fonts/OpenSans-Semibold-webfont.woff2 \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/images/ajax-loader.gif \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/images/icons-18-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/images/icons-18-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/images/icons-36-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/images/icons-36-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/jquery.mobile-1.4.5.min.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/jquery.mobile.external-png-1.4.5.min.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/jquery.mobile.icons-1.4.5.min.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/jquery.mobile.inline-png-1.4.5.min.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/jquery.mobile.inline-svg-1.4.5.min.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/jquery.mobile.structure-1.4.5.min.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/jquery.mobile.theme-1.4.5.min.css \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/ajax-loader.gif \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/action-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/action-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/alert-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/alert-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-d-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-d-l-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-d-l-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-d-r-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-d-r-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-d-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-l-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-l-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-r-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-r-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-u-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-u-l-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-u-l-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-u-r-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-u-r-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/arrow-u-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/audio-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/audio-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/back-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/back-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/bars-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/bars-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/bullets-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/bullets-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/calendar-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/calendar-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/camera-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/camera-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/carat-d-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/carat-d-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/carat-l-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/carat-l-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/carat-r-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/carat-r-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/carat-u-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/carat-u-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/check-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/check-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/clock-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/clock-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/cloud-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/cloud-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/comment-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/comment-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/delete-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/delete-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/edit-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/edit-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/eye-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/eye-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/forbidden-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/forbidden-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/forward-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/forward-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/gear-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/gear-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/grid-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/grid-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/heart-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/heart-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/home-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/home-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/info-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/info-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/location-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/location-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/lock-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/lock-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/mail-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/mail-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/minus-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/minus-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/navigation-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/navigation-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/phone-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/phone-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/plus-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/plus-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/power-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/power-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/recycle-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/recycle-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/refresh-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/refresh-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/search-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/search-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/shop-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/shop-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/star-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/star-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/tag-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/tag-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/user-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/user-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/video-black.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-png/video-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/action-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/action-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/alert-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/alert-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-d-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-d-l-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-d-l-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-d-r-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-d-r-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-d-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-l-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-l-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-r-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-r-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-u-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-u-l-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-u-l-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-u-r-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-u-r-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/arrow-u-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/audio-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/audio-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/back-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/back-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/bars-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/bars-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/bullets-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/bullets-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/calendar-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/calendar-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/camera-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/camera-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/carat-d-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/carat-d-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/carat-l-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/carat-l-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/carat-r-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/carat-r-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/carat-u-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/carat-u-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/check-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/check-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/clock-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/clock-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/cloud-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/cloud-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/comment-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/comment-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/delete-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/delete-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/edit-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/edit-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/eye-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/eye-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/forbidden-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/forbidden-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/forward-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/forward-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/gear-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/gear-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/grid-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/grid-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/heart-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/heart-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/home-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/home-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/info-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/info-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/location-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/location-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/lock-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/lock-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/mail-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/mail-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/minus-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/minus-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/navigation-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/navigation-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/phone-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/phone-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/plus-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/plus-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/power-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/power-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/recycle-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/recycle-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/refresh-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/refresh-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/search-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/search-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/shop-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/shop-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/star-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/star-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/tag-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/tag-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/user-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/user-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/video-black.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/css/themes/default/images/icons-svg/video-white.svg \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/img/dark_stripes.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/img/dark_stripes_@2X.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/img/small-vz-logo-white.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/img/vz-button-sprite.png \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/img/vz-icon-sprite.gif \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/collections \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/data \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/indexq.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/main.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/models \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/routers \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/collections/JobsCollection.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/collections/ProfilesCollection.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/collections/SubscriptionCollection.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/data/accounts \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/data/accounts/456 \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/data/accounts/5125551234 \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/data/accounts/accounts.json \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/data/accounts/smuser \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/backbone-min.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/backbone-min.map \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/backbone.touch.min.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/bootstrap.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/classie.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/cordova.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/cordova_plugins.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/jquery.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/jquery.mobile-1.4.5.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/ladda.min.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/lodash-min.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/pageslider.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/require-min.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/spin.min.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/lib/text.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/models/Account.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/models/AccountList.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/models/CategoryModel.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/models/Job.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/models/Login.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/models/Profile.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/models/Subscription.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/routers/mobileRouter.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/AccountListView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/ActiveAccountDetailsView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/JobDetailsView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/JobListView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/LoginView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/MenuView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/ProfileDetailsView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/ProfileListView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/SubscriptionDetailsView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/SubscriptionListView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/js/views/WaitView.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins/com.telerik.plugins.nativepagetransitions \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins/org.apache.cordova.dialogs \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins/com.telerik.plugins.nativepagetransitions/www \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins/com.telerik.plugins.nativepagetransitions/www/NativePageTransitions.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins/org.apache.cordova.dialogs/www \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins/org.apache.cordova.dialogs/www/android \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins/org.apache.cordova.dialogs/www/notification.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/plugins/org.apache.cordova.dialogs/www/android/notification.js \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/AccountList.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/ActiveAccountDetails.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/JobDetails.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/JobList.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/Login.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/Menu.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/ProfileDetailsTemplate.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/ProfileList.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/Progress.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/SubscriptionDetailsTemplate.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/assets/www/templates/SubscriptionList.html \
/Users/elonmitchell/Desktop/Trash/Verizon/Subscriber-App/platforms/android/ant-build/AndroidManifest.xml \
